apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component_name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.component_name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}